language : android

jdk : oraclejdk8

android:
  component:
  -platform-tools
  -tools
  -build-tools-23.0.3
  -android-23
  -extra-android-m2repository

before_install:
  -chmod +x gradlew

script: ./gradlew build
